stages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: cartblanche22-dev

services:
  - redis:latest

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche22-dev
    script:
        - sudo docker image prune -a -f
        # - docker build -t cartblanche22:latest .
        # - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .

deploy job:
    only:
        - master

    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche22-dev
    script:
        #- docker run -d -p 0.0.0.0:5068:5000 cartblanche22:latest
        # - docker stop cartblanche22-dev
        # - docker rm cartblanche22-dev
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.2.${CI_JOB_ID}" .
        # - docker stop cartblanche22-dev
        # - docker rm cartblanche22-dev
        # - docker network create my_app
        # - docker run --net my_app --name redis -d redis 
        - docker run --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:5067:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.2.${CI_JOB_ID}
        #- docker run --name redis -p 0.0.0.0:6379:6379 -d redis
    services:
        - redis:latest
