stages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: cartblanche22-dev

services:
  - redis:latest

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche22-dev
    script:
        - sudo docker image prune -a -f
        # - docker build -t cartblanche22:latest .
        # - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .

deploy job:
    only:
        - master

    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche22-dev
    script:
        #- docker run -d -p 0.0.0.0:5068:5000 cartblanche22:latest
        # - docker stop cartblanche22-dev
        # - docker rm cartblanche22-dev
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        # - docker stop cartblanche22-dev
        # - docker rm cartblanche22-dev
        # - docker network create -d bridge ${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
        - docker run --name redis2 -p 0.0.0.0:6380:6379 -d redis --port 6380
        #- mkdir -p /tmp/logs_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
        - docker run --privileged -v /tmp/logs_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}:/tmp/logs -v /etc/localtime:/etc/localtime:ro --name ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME} -d -p 0.0.0.0:5066:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
        
    services:
        - redis:latest
