
variables:
    CI_PROJECT_NAME: molecule-shopping-cart

services:
  - redis:latest

deploy-dev job:
    only:
        - dev
    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche-dev
    script:
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        - docker stop ${CI_PROJECT_NAME}
        - docker rm ${CI_PROJECT_NAME}
        - docker stop redis
        - docker rm redis
        - docker run --net cartblanche --name redis -d redis
        - docker run --net cartblanche -v /nfs/db2/smallworld_anon_21Q4:/nfs/db3/private_smallworld_4th_gen/anon
                     -v /nfs/db4/smallworld-java:/export/db4/smallworld-java
                     -v /nfs/db3/private_smallworld_4th_gen/smallworld.cfg:/nfs/db3/private_smallworld_4th_gen/smallworld.cfg
                     -v /nfs/db3/private_smallworld_4th_gen/maps:/nfs/db3/private_smallworld_4th_gen/maps
                     -e CELERY_BROKER_URL=${CELERY_BROKER_URL} 
                     -e CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND} 
                     -e COMMON_DATABASE=${COMMON_DATABASE} 
                     -e MAIL_PASSWORD=${MAIL_PASSWORD} 
                     -e MAIL_SERVER=${MAIL_SERVER} 
                     -e MAIL_USERNAME=${MAIL_USERNAME} 
                     -e SECRET_KEY=${SECRET_KEY} 
                     -e TIN_DATABASE=${TIN_DATABASE} 
                     -e ZINC_SMALL_WORLD_SERVER=${ZINC_SMALL_WORLD_SERVER} 
                     -e ZINC22_DATABASE=${ZINC22_DATABASE} 
                     -e GOOGLE_API_KEY=${GOOGLE_API_KEY} 
                     -e GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} 
                     --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:5068:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
       
deploy-live job:
    only:
        - master
    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche2
    script:
        - sudo docker image prune -a -f
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        - docker stop ${CI_PROJECT_NAME}
        - docker rm ${CI_PROJECT_NAME}
        - docker stop redis
        - docker rm redis
        - docker run --net cartblanche --name redis -d redis
        - docker run --net cartblanche -v /nfs/db2/smallworld_anon_21Q4:/nfs/db3/private_smallworld_4th_gen/anon
                     -v /export/db4/smallworld-java:/export/db4/smallworld-java
                     -v /nfs/db3/private_smallworld_4th_gen/smallworld.cfg:/nfs/db3/private_smallworld_4th_gen/smallworld.cfg
                     -v /nfs/db3/private_smallworld_4th_gen/maps:/nfs/db3/private_smallworld_4th_gen/maps
                     -e CELERY_BROKER_URL=${CELERY_BROKER_URL} 
                     -e CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND} 
                     -e COMMON_DATABASE=${COMMON_DATABASE} 
                     -e MAIL_PASSWORD=${MAIL_PASSWORD} 
                     -e MAIL_SERVER=${MAIL_SERVER} 
                     -e MAIL_USERNAME=${MAIL_USERNAME} 
                     -e SECRET_KEY=${SECRET_KEY} 
                     -e TIN_DATABASE=${TIN_DATABASE} 
                     -e ZINC_SMALL_WORLD_SERVER=${ZINC_SMALL_WORLD_SERVER} 
                     -e ZINC22_DATABASE=${ZINC22_DATABASE} 
                     -e GOOGLE_API_KEY=${GOOGLE_API_KEY} 
                     -e GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} 
                     --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:5068:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
