tages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: molecule-shopping-cart

services:
  - redis:latest

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche2
    script:
        - sudo docker image prune -a -f
       
deploy job:
    only:
        - master
    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche2
    script:
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        - docker stop cartblanche-dev
        - docker rm cartblanche-dev
        - docker run --net cartblanche-dev -v /nfs/db2/smallworld_anon_21Q4:/nfs/db3/private_smallworld_4th_gen/anon
                     -v /home/s_jcastanon/smallworld-java:/home/s_jcastanon/smallworld-java
                     -v /nfs/db3/private_smallworld_4th_gen/smallworld.cfg:/nfs/db3/private_smallworld_4th_gen/smallworld.cfg
                     -v /nfs/db3/private_smallworld_4th_gen/maps:/nfs/db3/private_smallworld_4th_gen/maps
                     --name cartblanche-dev -d -p 0.0.0.0:5067:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
