stages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: cartblanche22

services:
  - redis:latest

  

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche2
    script:
        - sudo docker image prune -a -f
        # - docker build -t cartblanche22:latest .
        # - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .

deploy job:
    only:
        - master

    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche2
    script:
        #- docker run -d -p 0.0.0.0:5068:5000 cartblanche22:latest
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        - docker network prune -f
        # - docker stop cartblanche22
        # - docker rm cartblanche22
        - docker network create my_app
        - docker run --net my_app --name redis -d redis 
        - docker run --net my_app --name ${CI_PROJECT_NAME} -d -p 127.0.0.1:5067:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
    services:
        - redis:latest
