stages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: molecule-shopping-cart

services:
  - redis:latest

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche2
    script:
        - sudo docker image prune -a -f    

deploy job:
    only:
        - master
    stage: deploy
    services:
        - redis:latest
    tags:
        - cartblanche2
    script:
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        - docker stop ${CI_PROJECT_NAME}
        - docker rm ${CI_PROJECT_NAME}
        - docker stop redis
        - docker rm redis
        - docker run --net cartblanche --name redis -d redis
        - docker run --net cartblanche -v /nfs/db2/smallworld_anon_21Q4:/nfs/db3/private_smallworld_4th_gen/anon
                     -v /export/db4/smallworld-java:/export/db4/smallworld-java
                     -v /nfs/db3/private_smallworld_4th_gen/smallworld.cfg:/nfs/db3/private_smallworld_4th_gen/smallworld.cfg
                     -v /nfs/db3/private_smallworld_4th_gen/maps:/nfs/db3/private_smallworld_4th_gen/maps
                     --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:5068:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
