stages:
  - build
  - deploy

variables:
    CI_PROJECT_NAME: cartblanche22

build job:
    only:
        - master
    stage: build
    tags:
        - cartblanche2
    script:
        - sudo docker image prune -a -f
        # - docker build -t cartblanche22:latest .
        # - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .

deploy job:
    only:
        - master
    stage: deploy
    tags:
        - cartblanche2
    script:
        #- docker run -d -p 0.0.0.0:5068:5000 cartblanche22:latest
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
        # - docker stop cartblanche22
        # - docker rm cartblanche22
        - docker run --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:5068:5000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}
