"""migrating

Revision ID: 111bf03e4e7f
Revises: 1c7dc601ff7d
Create Date: 2019-11-12 10:37:55.444409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111bf03e4e7f'
down_revision = '1c7dc601ff7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('cat_name', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_vendors_cat_name'), 'vendors', ['cat_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_cat_name'), table_name='vendors')
    op.drop_column('vendors', 'cat_name')
    # ### end Alembic commands ###
