"""price changed to float

Revision ID: 1c7dc601ff7d
Revises: acd90b0fd923
Create Date: 2019-11-07 10:57:54.127192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7dc601ff7d'
down_revision = 'acd90b0fd923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('cat_name', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_vendors_cat_name'), 'vendors', ['cat_name'], unique=False)
    op.drop_index('ix_vendors_company_name', table_name='vendors')
    op.drop_column('vendors', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('company_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_vendors_company_name', 'vendors', ['company_name'], unique=False)
    op.drop_index(op.f('ix_vendors_cat_name'), table_name='vendors')
    op.drop_column('vendors', 'cat_name')
    # ### end Alembic commands ###
