"""empty message

Revision ID: 313b0f42c305
Revises: 
Create Date: 2019-11-22 10:14:57.556943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b0f42c305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('activeCart', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cart_fk', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('compound_img', sa.String(length=256), nullable=True),
    sa.Column('database', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cart_fk'], ['carts.cart_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_identifier'), 'items', ['identifier'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item_fk', sa.Integer(), nullable=True),
    sa.Column('cat_name', sa.String(length=120), nullable=True),
    sa.Column('pack_quantity', sa.Float(), nullable=True),
    sa.Column('purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('supplier_code', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('cat_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_fk'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_cat_name'), 'vendors', ['cat_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_cat_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_items_identifier'), table_name='items')
    op.drop_table('items')
    op.drop_table('user_roles')
    op.drop_table('carts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
