"""empty message

Revision ID: 3453e63c7ae0
Revises: 389ffc40030b
Create Date: 2019-12-06 16:09:49.386441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3453e63c7ae0'
down_revision = '389ffc40030b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('compound_img', sa.String(length=512), nullable=True))
    op.drop_column('items', 'compound_img2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('compound_img2', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('items', 'compound_img')
    # ### end Alembic commands ###
