"""empty message

Revision ID: 389ffc40030b
Revises: 313b0f42c305
Create Date: 2019-12-06 16:09:34.903903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389ffc40030b'
down_revision = '313b0f42c305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('compound_img2', sa.String(length=512), nullable=True))
    op.drop_column('items', 'compound_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('compound_img', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('items', 'compound_img2')
    # ### end Alembic commands ###
