"""empty message

Revision ID: 45f092da5428
Revises: e34c02dc5cbb
Create Date: 2019-11-13 16:29:29.941784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f092da5428'
down_revision = 'e34c02dc5cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activeCart', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activeCart')
    # ### end Alembic commands ###
