"""empty message

Revision ID: 50ccd6a22bfd
Revises: b48ac221d65d
Create Date: 2019-11-13 15:24:26.794354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ccd6a22bfd'
down_revision = 'b48ac221d65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activeCart',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activeCart',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
