"""user preference added

Revision ID: 5f100365d41f
Revises: 3453e63c7ae0
Create Date: 2020-01-24 11:28:52.028193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f100365d41f'
down_revision = '3453e63c7ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availableVendors',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('cat_id_fk', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(length=120), nullable=True),
    sa.Column('bb', sa.Boolean(), nullable=True),
    sa.Column('purchasable', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('user_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['availableVendors.vendor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vendors')
    op.drop_table('availableVendors')
    # ### end Alembic commands ###
