"""shipping field added

Revision ID: acd90b0fd923
Revises: e8d8fadcabb3
Create Date: 2019-11-05 14:05:18.159275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd90b0fd923'
down_revision = 'e8d8fadcabb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('shipping', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'shipping')
    # ### end Alembic commands ###
