"""empty message

Revision ID: b48ac221d65d
Revises: 
Create Date: 2019-11-13 15:11:31.603510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48ac221d65d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('activeCart', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('one', 'two', 'three', 'four', 'five', 'six', 'seven', name='cartstatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cart_fk', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('compound_img', sa.String(length=256), nullable=True),
    sa.Column('database', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cart_fk'], ['carts.cart_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_identifier'), 'items', ['identifier'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item_fk', sa.Integer(), nullable=True),
    sa.Column('cat_name', sa.String(length=120), nullable=True),
    sa.Column('pack_quantity', sa.Float(), nullable=True),
    sa.Column('purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('supplier_code', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('cat_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_fk'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_cat_name'), 'vendors', ['cat_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_cat_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_items_identifier'), table_name='items')
    op.drop_table('items')
    op.drop_table('carts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
