"""vendor table deleted

Revision ID: e1a7d974d6f6
Revises: 4d45670d5451
Create Date: 2019-10-21 14:15:59.760736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a7d974d6f6'
down_revision = '4d45670d5451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    op.add_column('item', sa.Column('cat_id_fk', sa.String(length=120), nullable=True))
    op.add_column('item', sa.Column('company_name', sa.String(length=120), nullable=True))
    op.add_column('item', sa.Column('delivery_time', sa.String(length=120), nullable=True))
    op.add_column('item', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('supplier_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'supplier_code')
    op.drop_column('item', 'price')
    op.drop_column('item', 'delivery_time')
    op.drop_column('item', 'company_name')
    op.drop_column('item', 'cat_id_fk')
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('supplier_code', sa.VARCHAR(length=120), nullable=True),
    sa.Column('cat_id_fk', sa.VARCHAR(length=120), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('delivery_time', sa.VARCHAR(length=120), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('selected', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('selected IN (0, 1)'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
