"""empty message

Revision ID: e34c02dc5cbb
Revises: 50ccd6a22bfd
Create Date: 2019-11-13 15:59:31.571312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34c02dc5cbb'
down_revision = '50ccd6a22bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activeCart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activeCart', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
